# Use root/example as user/password credentials
version: '3.4'

volumes: 
  mongodata:
    name: "MongoData-WebDB"

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27018:27017
    volumes: 
       - mongodata:/data/db 

  bankingapi:
    image: bankingapi
    container_name: banking-api
    build: 
      context: ./
      dockerfile: Dockerfile.bankingapi
    ports: 
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongo

  bankingclient:
    image: bankingclient
    container_name: banking-client
    build: 
      context: ./
      dockerfile: Dockerfile.bankingclient
    ports: 
      - 5005:80
    environment:
     - BackEndUri=http://banking-api
     - RelLoginUri=/api/user/login
     - RelLogoutUri=/api/user/logout
     - RelRegisterUri=/api/user/register
     - BankingApiGetAllAccounts=http://banking-api/api/banking/accounts/getall
     - BankingApiGetOneAccountRegex=http://banking-api/api/banking/account/getoneregex
     - BankingApiGetAccountsRegex=http://banking-api/api/banking/accounts/getaccountsregex
     - BankingApiPostAccount=http://banking-api/api/banking/account/create
     - BankingApiUpdateAccount=http://banking-api/api/banking/account/update
     - BankingApiDeleteAccount=http://banking-api/api/banking/account/delete
    depends_on: 
      - bankingapi

  